### ISSUE TITLE
No attribute Prompt

### ISSUE THREAD

**Issue by bookandlover** [pytorch/torchchat#1002]
### 🐛 Describe the bug

AttributeError: 'Namespace' object has no attribute 'prompt'

### Versions

python collect_env.py

Collecting environment information...
PyTorch version: 2.5.0.dev20240710
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 15.0 (arm64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: version 3.30.1
Libc version: N/A

Python version: 3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)] (64-bit runtime)
Python platform: macOS-15.0-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Max

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.5.0.dev20240710
[pip3] torchao==0.3.1
[conda] Could not collect

**Comment by YeonwooSung** [comment]
According to the `cli.py` file, the argument 'prompt' is only added for "generate", but the initializer of the server requires the prompt

```python
# Add CLI Args specific to user prompted generation
# Include prompt and num_sample args when the subcommand is generate
def _add_generation_args(parser, verb: str) -> None:
    generator_parser = parser.add_argument_group(
        "Generation", "Configs for generating output based on provided prompt"
    )

    if verb == "generate":
        generator_parser.add_argument(
            "--prompt",
            type=str,
            default="Hello, my name is",
            help="Input prompt for manual output generation",
        )
        generator_parser.add_argument(
            "--num-samples",
            type=int,
            default=1,
            help="Number of samples",
        )
```

**Comment by Jack-Khuu** [comment]
Ah looks like i missed this in https://github.com/pytorch/torchchat/pull/987

Thanks for flagging

**Comment by Jack-Khuu** [comment]
Merging with https://github.com/pytorch/torchchat/issues/1003

thanks again for flagging
