### ISSUE TITLE
torchchat有没有推理加速的功能，目前不支持qwen1.5,qwen2系列吗？

### ISSUE THREAD

**Issue by yawzhe** [pytorch/torchchat#1010]
### 🐛 Describe the bug

torchchat有没有推理加速的功能，目前不支持qwen1.5,qwen2系列吗？优势在哪里？

### Versions

torchchat有没有推理加速的功能，目前不支持qwen1.5,qwen2系列吗？

**Comment by byjlw** [comment]
Yes there is acceleration for some chipsets, primarily CUDA and MPS for desktop and server. More for edge using ET. 
We have not tested Qwen1.5 but it may just work. Feel free free to add it to the models file  and give it a go. 
https://github.com/pytorch/torchchat/blob/main/config/data/models.json
