### ISSUE TITLE
Support for quantized llm for smaller memory devices

### ISSUE THREAD

**Issue by jhetuts** [pytorch/torchchat#1024]
### 🚀 The feature, motivation and pitch

I believe, this is what ollama's one huge advantage. This can also encourage devs to go test llm which they can run on their machine's capabilities. Like me, I have my m1 16gb, I cannot really enjoy testing the meta llms, especially the llama3.1

**Comment by larryliu0820** [comment]
Hi @jhetuts thanks for providing feedback! Can you give a specific example on what quantized llm you are referring to? For llama3.1 we have a few quantization options and you can refer to this [readme](https://github.com/pytorch/torchchat/blob/main/docs/quantization.md#eager-mode). m1 16gb should be able to run llama3.1 8B model with quantization.

**Comment by jhetuts** [comment]
Got it @larryliu0820 , I've been testing with this. Thanks!
