### ISSUE TITLE
llama vision model requires an image

### ISSUE THREAD

**Issue by byjlw** [pytorch/torchchat#1213]
### 🐛 Describe the bug

both generate and the api require an image to be used when sending a prompt

Things were not implemented for text only.

### Versions

N/A

**Comment by Jack-Khuu** [comment]
https://github.com/pytorch/torchchat/pull/1216

**Comment by Gasoonjia** [comment]
https://github.com/pytorch/torchchat/pull/1216 has been merged and we can support text-only now. Close it.
