### ISSUE TITLE
[easy] Outdated Android README Image

### ISSUE THREAD

**Issue by Jack-Khuu** [pytorch/torchchat#1316]
### 🐛 Describe the bug

https://github.com/pytorch/torchchat/commit/c867660049c6bbceefbaa2341f7d9c79832f2f7f introduced a new and improved Android app, but the README image still shows the old app in https://github.com/pytorch/torchchat?tab=readme-ov-file#deploy-and-run-on-android

We should update this

### Versions

NA

**Comment by Jack-Khuu** [comment]
cc: @kirklandsign

**Comment by kirklandsign** [comment]
https://github.com/pytorch/torchchat/pull/1317
