### ISSUE TITLE
`weights_only` default flip for `torch.load`

### ISSUE THREAD

**Issue by mikaylagawarecki** [pytorch/torchchat#1356]
### 🐛 Describe the bug

We've flipped the default for the `weights_only` argument in `torch.load` to `True` in `pytorch/pytorch`, see [here](https://dev-discuss.pytorch.org/t/bc-breaking-change-torch-load-is-being-flipped-to-use-weights-only-true-by-default-in-the-nightlies-after-137602/2573) for details + [documentation](https://pytorch.org/docs/main/notes/serialization.html#torch-load-with-weights-only-true) and this is coming in `torch 2.6`.

This is expected to be quite a BC-breaking change, especially if any `torch.load` calls  in `torchchat` are not loading state_dicts of plain tensors.

We should make sure that all the `torch.load` calls in `torchchat` are still working.

For example, [this one](https://github.com/pytorch/torchchat/blob/e30aaa06511bf490157544054410c468a6382d0f/torchchat/distributed/checkpoint.py#L95) does not explicitly set `weights_only` so might now be failing since `torchchat` doesn't use pytorch nightlies in CI

cc @Jack-Khuu

### Versions

main

**Comment by Jack-Khuu** [comment]
Fixed in pin bump
