### ISSUE TITLE
Update dead link in https://github.com/pytorch/torchchat/blob/main/docs/quantization.md

### ISSUE THREAD

**Issue by yanbing-j** [pytorch/torchchat#1385]
### 🐛 Describe the bug

There is a dead link https://github.com/pytorch/torchchat/blob/main/torchchat/utils/quantize.py#L1260-L1266 in https://github.com/pytorch/torchchat/blob/main/docs/quantization.md like `See the available quantization schemes [here](https://github.com/pytorch/torchchat/blob/main/torchchat/utils/quantize.py#L1260-L1266).`. Could you please help update it to show the quantization schemes examples?

### Versions

#

**Comment by yanbing-j** [comment]
cc @mikekgfb @mingfeima

**Comment by yanbing-j** [comment]
In main branch, torchchat/utils/quantize.py only has 942 lines.

**Comment by Jack-Khuu** [comment]
Ah good catch
