### ISSUE TITLE
[Feature request] Stop Executorch dump of graph, unless there some debug flag

### ISSUE THREAD

**Issue by mikekgfb** [pytorch/torchchat#187]
The graph is basically spam that can't be analyzed by the users and typically so long that even if you want to analyze it, you can't scoll back to a place of interest.  Create an option (say ET_LOG, or reuse TORCHLOGS which is the new way of controlling torch logging for all parts of pytorch, including torch.export, giving our users a single interface.)

https://github.com/pytorch/torchat/actions/runs/8681411543/job/23803982796?pr=173

**Comment by byjlw** [comment]
This is resolved.
