### ISSUE TITLE
[PRE-LAUNCH] `./scripts/install_et.sh $ENABLE_ET_PYBIND` errored out with exit status 1

### ISSUE THREAD

**Issue by mikekgfb** [pytorch/torchchat#577]
@ali-khosh user report:

Mobile execution. When trying to run ./scripts/install_et.sh $ENABLE_ET_PYBIND I get the following error
ERROR: Command errored out with exit status 1: /Users/ali/Desktop/torchchat/torchchat/.venv/bin/python3 /Users/ali/Desktop/torchchat/torchchat/.venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/fk/fwp4jmd113z2n7r0bdjt_zq00000gn/T/tmpnjgun42u Check the logs for full command output.

**Comment by Jack-Khuu** [comment]
Closing non-updated task of 2 month
