### ISSUE TITLE
Running `torchchat export` with just the model name does not error out

### ISSUE THREAD

**Issue by malfet** [pytorch/torchchat#969]
### 🐛 Describe the bug

Running `python torchchat.py export stories15M` does not error out, nor generates any export files, though it should have?
```shell
% python torchchat.py export stories15M; echo $?
lm_eval is not installed, GPTQ may not be usable
Using device=mps
Warning! Device MPS not supported for export. Exporting for device CPU.
Loading model...
Time to load model: 0.02 seconds
-----------------------------------------------------------
0
```

### Versions

No idea, where is the torchchat version defined?

**Comment by Jack-Khuu** [comment]
Good catch, an export path should be required

> the torchchat version defined?

There is no current torchchat version

**Comment by mike94043** [comment]
Export was designed to take a set of export options (as in the mathematical definition of set, and including the empty set) and export to all of them. 

That being said, some transformations only work for one of the backends, and then it would issue an error. Sadly, too many quantization solutions are bespoke, which undermines that approach atm, although I was hoping to use this to check/drive multi-export. In that n-export model, n=0 was a possible choice, but may not be what users expected.

In any event, #970  changes this, so we might close this issue?
